apiVersion: cilium.io/v2
kind: CiliumNetworkPolicy
metadata:
  name: api-policy
  namespace: tenant-a
spec:
  endpointSelector:
    matchLabels:
      app: api
  egress:
    - toFQDNs:
        - matchName: s3.aws.com
    - toFQDNs:
        - matchName: api.github.com
      toPorts:
        - ports:
            - port: '443'
    - toEndpoints:
        - matchLabels:
            app: payment
  ingress:
    - {}
