name: "Isovalent Guardrails"

on:
  push:
    branches: [ master ]
  pull_request:
    # The branches below must be a subset of the branches above
    branches: [ master ]
      
jobs:
  analyze:
    name: Analyze
    runs-on: ubuntu-20.04    
    permissions:
      actions: read
      contents: read
      security-events: write
    strategy:
      fail-fast: false
    steps:
      - uses: actions/checkout@v2
      - uses: docker://quay.io/isovalent/policy-guardrails-ci:be9a3331423034df39c0bc9fd69ce33f7d7e8663
        with:
          args: node -- /app/app.js --policies ./policies/*.yaml --guardrails ./.github/guardrails.yaml --format github --output ./results.sarif
      - uses: github/codeql-action/upload-sarif@v1
        with:
          sarif_file: results.sarif
