name: "Analyze"

on:
  push:
    branches: [ master ]
  pull_request:
    # The branches below must be a subset of the branches above
    branches: [ master ]
      
jobs:
  analyze:
    name: Isovalent Guardrails
    runs-on: ubuntu-20.04    
    permissions:
      actions: read
      contents: read
      security-events: write
    strategy:
      fail-fast: false
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        
      - name: Run Isovalent Guardrails 
        uses: docker://quay.io/isovalent/policy-guardrails-ci:56aab21424db0e31d35f1026127ae1e289cf96c8
        with:
          args: node -- /app/app.js --policies ./policies/*.yaml --guardrails ./.github/guardrails.yaml --format github --output ./results.sarif
      
      - name: Upload results
        if: ${{ always() }}
        uses: github/codeql-action/upload-sarif@v1
        with:
          sarif_file: results.sarif
